#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 11 18:24:53 2020

@author: hat
"""

from sklearn.base import BaseEstimator
from sklearn.base import TransformerMixin

class 4_transform(BaseEstimator, TransformerMixin):
    
    def __init__(self, X):
        self.X = X
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        return X+1
    
    
